pipeline {
    agent any

    parameters{
        
        // AWS Configurations
        string(defaultValue: "ap-south-1", description: "AWS Region for S3 Bucket", name: "s3_bucket_region")
        choice(choices: ["ayush-artifact-bucket", "my-hg-destination-bkt"], description: "Name of the S3 Bucket to upload the Artifacts", name: "s3_bucket_name")

        // Jenkins Configurations
        string(defaultValue: "OLD_AWS_ayush-cli", description: "Name of the Credentials Profile in jenkins DB", name: "credentials_in_jenkins")
        string(defaultValue: "target", description: "Path of the folder from where the Artifacts needs to be picked", name: "folder_path_for_artifactory")        
        
        // Project Configurations
        string(defaultValue: "https://github.com/jenkins-docs/simple-java-maven-app.git", description: "Git URL of the Maven project", name: "git_url")
        
    }

    stages{
        stage("Cleanup"){
            steps{
                deleteDir()                
            }
        }
        stage("Clone Repo"){
            steps{
                sh "git clone ${params.git_url}"
            }
        }
        stage("Build"){
            steps{
                dir("simple-java-maven-app"){
                    sh "mvn clean install"
                }                
            }
        }
        // stage("Test"){
        //     steps{
        //         dir("simple-java-maven-app"){
        //             sh "mvn test"
        //         }                
        //     }
        // }
        stage("Upload to S3"){
            steps{
                dir("simple-java-maven-app"){
                    // pwd()
                    withAWS(region: "${params.s3_bucket_region}", credentials: "${params.credentials_in_jenkins}"){
                        s3Upload(bucket: "${params.s3_bucket_name}", workingDir: "${params.folder_path_for_artifactory}", includePathPattern: '*.jar')
                    }
                }
            }
        }
        stage("Upload built files to S3"){
            steps{
                dir("simple-java-maven-app"){
                    echo "pwd"
                    withAWS(region: "${params.s3_bucket_region}", credentials: "${params.credentials_in_jenkins}"){
                        s3Upload(bucket: "${params.s3_bucket_name}", workingDir: '', includePathPattern: '**/*.*')
                    }
                }
            }
        }
    }
}