pipeline {

    agent any

    stages{
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }
        stage("Clone Repo"){
            steps{
                    git credentialsId: 'git-indayush-password', url: 'https://bitbucket.org/hgrailsbackend/ror-hello-world.git', branch: 'master'
                    sh "git checkout demo"
                    sh "ls -lath"
            }
        }
    }

}