pipeline {

    agent any

    stages{
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }

        stage("Clone Repo"){
            steps{
                sh "git clone https://github.com/indayush/ror-hello-world.git"
            }
        }

        stage("Build"){                
            steps{
                dir("ror-hello-world"){
                    sh '''#!/bin/bash
                        source ~/.rvm/scripts/rvm
                        source ~/.bashrc
                        

                        git branch
                        git checkout demo
                        echo "<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>"
                        git branch
                        ls -la                        
                        '''
                }
                
            }           
        }

    }

}
