pipeline {

    agent any
    
    parameters{
    
        string(
                name: "s_Branch_Name", defaultValue: "demo",
                description: "Enter Brnach Name")

        string(
                name: "git_url", defaultValue: "https://github.com/indayush/ror-hello-world.git", 
                description: "Git URL of the project")

        choice(
                name: "select_env", choices: ["DEV", "QA", "QA1", "PROD"], 
                description: "Select Environment: ")
    }

    // Entire Pipeline Timeout value
    options{
        timeout(time: 15, unit: 'MINUTES')
    }

    stages{
        stage("Clean Up"){
            // Max Timeout value for this Stage            
            options{
                timeout(time: 1, unit: 'MINUTES')
            }
            steps{
                deleteDir()
            }
        }

        stage("Targeting Environment"){
            steps{
                sh "echo ${params.select_env} Environment is selected"
            }
        }

        stage("Clone Repo"){
            steps{
                sh "git clone ${params.git_url}"
            }
        }

        stage("Checkout Branch"){
            steps{
                dir("ror-hello-world"){
                    sh "git checkout ${params.s_Branch_Name}"
                    sh "git branch"
                    sh '''#!/bin/bash
                        source ~/.rvm/scripts/rvm
                        source ~/.bashrc

                        rvm list
                        rails -v
                        ruby -v 
                        ls -lah
                        pwd            
                    '''
                }
            }
        }

        stage("Zip the latest code"){
            steps{
                
                sh "ls"
                sh "zip -r ${params.s_Branch_Name}.zip ror-hello-world"
                sh "pwd"
                sh "ls -lh"
            }
        }

    }


    post {
        failure {
            // Runs ONLY in case of failure, We can have simple Notification/'git blame' on build history :)
            // currentBuild.displayName = 'This build needs help!!!'
            // buildDescription("Committer: ${GERRIT_PATCHSET_UPLOADER_NAME}")

            sh("echo FAILURE FOUND")
        }
    }

}
