pipeline {
    agent any 

    stages{
       stage("Trigger Lambda"){
            steps{
                
                def result = invokeLambda(
                    functionName: 'demo-function',
                    payload: [ "key": "value", "anotherkey" : [ "another", "value"] ]
                )

            }
        }
    }
}